unit FichaTractaments;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  ExtCtrls, ComCtrls, Db, DBTables, HYSql, HYPanels, HYEdit, StdCtrls,
  DBCtrls, HYLabel, Grids, DBGrids, HYGrids, Variants, HYDialogConsulta;

type
  TwFichaTractaments = class(TForm)
    Splitter1: TSplitter;
    Panel2: TPanel;
    dsTract: TDataSource;
    HYBarra1: THYBarra;
    HYArea1: THYArea;
    Ed_Tract_C_Tractament: THYEdit;
    Ed_Tract_C_Historia: THYEdit;
    Ed_Tract_C_Prestacio: THYEdit;
    Ed_Tract_Data_Ingres: THYEdit;
    Ed_Tract_C_Coordinador: THYEdit;
    Ed_Tract_Durada: THYEdit;
    Eti_Tract_Fili_NomComplet: THYLabel;
    Eti_Tract_Fili_SEXO: THYLabel;
    Eti_Tract_Fili_EsViu: THYLabel;
    Eti_Tract_Prestacio_N_Prestacio: THYLabel;
    Eti_Tract_Coordinador_Nom: THYLabel;
    Ed_Tract_Hora: THYEdit;
    PageControl1: TPageControl;
    TabSheet1: TTabSheet;
    TabSheet2: TTabSheet;
    HYArea2: THYArea;
    Ed_Tract_Data_PreAlta: THYEdit;
    Ed_Tract_C_MetgePreAlta: THYEdit;
    Ed_Tract_Data_Alta: THYEdit;
    Ed_Tract_C_MetgeAlta: THYEdit;
    Eti_Tract_MetgePreAlta_Nom: THYLabel;
    Eti_Tract_MetgeAlta_Nom: THYLabel;
    HYArea3: THYArea;
    Ed_Tract_C_PrestacioOrigen: THYEdit;
    Ed_Tract_C_Motiu: THYEdit;
    Ed_Tract_C_Origen: THYEdit;
    Ed_Tract_C_HospitalOrigen: THYEdit;
    Ed_Tract_C_Caracter: THYEdit;
    Ed_Tract_C_Solicitud: THYEdit;
    Ed_Tract_C_LLit: THYEdit;
    Ed_Tract_C_Planta: THYEdit;
    Ed_Tract_C_Residencia: THYEdit;
    Ed_Tract_C_Destinacio: THYEdit;
    Ed_Tract_C_HospitalDesti: THYEdit;
    Ed_Tract_ComentariMetge: THYEdit;
    Ed_Tract_ComentariInfermeria: THYEdit;
    Eti_Tract_Destinacio_N_CodiTract: THYLabel;
    Eti_Tract_HtalDestinacio_N_Hospital: THYLabel;
    Eti_Tract_HtalDestinacio_Poblacio: THYLabel;
    TabSheet4: TTabSheet;
    TabSheet5: TTabSheet;
    TabSheet6: TTabSheet;
    HYArea6: THYArea;
    HYMemo1: THYMemo;
    Ed_Tract_EstatInformeAlta: THYEdit;
    Ed_Tract_Entrada: THYEdit;
    Ed_Tract_Sortida: THYEdit;
    TabSheet7: TTabSheet;
    HYMemo3: THYMemo;
    Eti_Tract_Origen_N_CodiTract: THYLabel;
    Eti_Tract_HtalOrigen_N_Hospital: THYLabel;
    Eti_Tract_HtalOrigen_Poblacio: THYLabel;
    Eti_Tract_Caracter_N_CodiTract: THYLabel;
    Eti_Tract_Solicitud_N_CodiTract: THYLabel;
    DiagI: THYSqlBrowse;
    DiagI_C_Tractament: TIntegerField;
    DiagI_Tipus: TStringField;
    DiagI_Ordre: TSmallintField;
    DiagI_C_Diagnostic: TStringField;
    DiagI_N_Diagnostic: TStringField;
    dsDiagI: TDataSource;
    DiagA: THYSqlBrowse;
    DiagA_C_Tractament: TIntegerField;
    DiagA_Tipus: TStringField;
    DiagA_Ordre: TSmallintField;
    DiagA_C_Diagnostic: TStringField;
    DiagA_N_Diagnostic: TStringField;
    dsDiagA: TDataSource;
    DBRichEdit1: TDBRichEdit;
    TabSheet8: TTabSheet;
    HYArea9: THYArea;
    Ed_Tract_C_CentreFac: THYEdit;
    Ed_Tract_C_Client: THYEdit;
    Ed_Tract_C_Delegacio: THYEdit;
    Ed_Tract_CaducaPermis: THYEdit;
    Ed_Tract_PercentatgePacient: THYEdit;
    Ed_Tract_Referencia: THYEdit;
    Ed_Tract_C_EstatFac: THYEdit;
    Eti_Tract_Centre_N_CentreFac: THYLabel;
    Eti_Tract_Client_N_Client: THYLabel;
    Eti_Tract_Delegacio_N_Delegacio: THYLabel;
    Check_Tract_Ambulancia: THYCheck;
    Ed_Tract_C_EsperaProgramada: THYEdit;
    Ed_Tract_C_Stock: THYEdit;
    Check_Tract_confirmstock: THYCheck;
    Ed_Tract_C_MetgePassi: THYEdit;
    Check_Tract_Passi: THYCheck;
    Ed_Tract_C_Metge_InfAlta: THYEdit;
    Ed_Tract_C_Proces: THYEdit;
    Ed_Tract_Fi_Proces: THYEdit;
    Eti_Tract_Client_Es_Unespa: THYLabel;
    Eti_Tract_Client_CodiUnespa: THYLabel;
    Ed_Tract_Data_Sinistre: THYEdit;
    Ed_Tract_Matricula_Vehicle: THYEdit;
    Ed_Tract_Metge_Proces: THYEdit;
    Panel3: TPanel;
    Panel4: TPanel;
    Panel5: TPanel;
    HYGrid1: THYGrid;
    HYBarra2: THYBarra;
    HYBarra3: THYBarra;
    HYGrid2: THYGrid;
    DeficitsI: THYSqlBrowse;
    DeficitsI_C_Tractament: TIntegerField;
    DeficitsI_Tipus: TStringField;
    DeficitsA: THYSqlBrowse;
    DeficitsA_C_Tractament: TIntegerField;
    DeficitsA_Tipus: TStringField;
    dsDeficitsI: TDataSource;
    dsDeficitsA: TDataSource;
    Panel9: TPanel;
    Panel11: TPanel;
    Panel13: TPanel;
    HYArea7: THYArea;
    Ed_Tract_C_DiagnosticNeurologicAlta: THYEdit;
    Ed_Tract_N_DiagnosticNeurologicAlta: THYEdit;
    Ed_Tract_C_DiagnosticAlta: THYEdit;
    Ed_Tract_N_DiagnosticAlta: THYEdit;
    Panel12: TPanel;
    HYGrid5: THYGrid;
    HYBarra7: THYBarra;
    dsDeficitsP: TDataSource;
    DeficitsP: THYSqlBrowse;
    DeficitsP_C_Tractament: TIntegerField;
    DeficitsP_Tipus: TStringField;
    dsDiagP: TDataSource;
    DiagP: THYSqlBrowse;
    DiagP_C_Tractament: TIntegerField;
    DiagP_Tipus: TStringField;
    DiagP_Ordre: TSmallintField;
    DiagP_C_Diagnostic: TStringField;
    DiagP_N_Diagnostic: TStringField;
    DiagP_C_Metge: TStringField;
    DiagP_Data: TDateTimeField;
    DiagI_C_Metge: TStringField;
    DiagI_Data: TDateTimeField;
    DiagA_C_Metge: TStringField;
    DiagA_Data: TDateTimeField;
    HYArea8: THYArea;
    Ed_Tract_C_DiagnosticNeurologicIngres: THYEdit;
    Ed_Tract_N_DiagnosticNeurologicIngres: THYEdit;
    Ed_Tract_C_DiagnosticIngres: THYEdit;
    Ed_Tract_N_DiagnosticIngres: THYEdit;
    DeficitsI_C_ICF: TStringField;
    DeficitsI_Qualificacio: TSmallintField;
    DeficitsI_C_Usuari: TStringField;
    DeficitsI_Data: TDateTimeField;
    DeficitsP_C_ICF: TStringField;
    DeficitsP_Qualificacio: TSmallintField;
    DeficitsP_C_Usuari: TStringField;
    DeficitsP_Data: TDateTimeField;
    DeficitsA_C_ICF: TStringField;
    DeficitsA_Qualificacio: TSmallintField;
    DeficitsA_C_Usuari: TStringField;
    DeficitsA_Data: TDateTimeField;
    Splitter4: TSplitter;
    Splitter5: TSplitter;
    Busca: TQuery;
    Panel14: TPanel;
    DBGrid1: TDBGrid;
    PageControl2: TPageControl;
    TabSheet9: TTabSheet;
    fHistoria: THYEditFiltro;
    fNom: THYEditFiltro;
    Panel15: TPanel;
    DBNavigator1: TDBNavigator;
    bAplicaFiltre: TButton;
    bNetejaFiltre: TButton;
    fTractament: THYEditFiltro;
    fDataIngres: THYEditFiltro;
    TabSheet10: TTabSheet;
    Memo: TMemo;
    Panel16: TPanel;
    DBNavigator2: TDBNavigator;
    dsBusca: TDataSource;
    Tract: THYSqlBrowse;
    Tract_C_Tractament: TIntegerField;
    Tract_C_Historia: TIntegerField;
    Tract_C_Prestacio: TStringField;
    Tract_C_PrestacioOrigen: TStringField;
    Tract_Data_Ingres: TDateTimeField;
    Tract_Hora: TStringField;
    Tract_C_Coordinador: TStringField;
    Tract_Data_PreAlta: TDateTimeField;
    Tract_C_MetgePreAlta: TStringField;
    Tract_Data_Alta: TDateTimeField;
    Tract_C_MetgeAlta: TStringField;
    Tract_Durada: TFloatField;
    Tract_Comentari: TMemoField;
    Tract_C_Motiu: TSmallintField;
    Tract_C_Origen: TSmallintField;
    Tract_C_HospitalOrigen: TSmallintField;
    Tract_C_Caracter: TSmallintField;
    Tract_C_Solicitud: TSmallintField;
    Tract_C_Destinacio: TSmallintField;
    Tract_C_HospitalDesti: TSmallintField;
    Tract_InformeAlta: TMemoField;
    Tract_EstatInformeAlta: TIntegerField;
    Tract_ComentariMetge: TStringField;
    Tract_ComentariInfermeria: TStringField;
    Tract_c_Residencia: TStringField;
    Tract_Entrada: TIntegerField;
    Tract_Sortida: TIntegerField;
    Tract_C_Frequencia: TStringField;
    Tract_C_FisioTerapeuta: TStringField;
    Tract_C_Terapeuta: TStringField;
    Tract_C_Cas: TSmallintField;
    Tract_Complicacions: TStringField;
    Tract_C_ProcesOrigen: TSmallintField;
    Tract_Frankel: TStringField;
    Tract_C_Codi_E: TStringField;
    Tract_N_Codi_E: TStringField;
    Tract_C_DiagnosticNeurologicIngres: TStringField;
    Tract_N_DiagnosticNeurologicIngres: TStringField;
    Tract_C_DiagnosticIngres: TStringField;
    Tract_N_DiagnosticIngres: TStringField;
    Tract_C_DiagnosticNeurologicAlta: TStringField;
    Tract_N_DiagnosticNeurologicAlta: TStringField;
    Tract_C_DiagnosticAlta: TStringField;
    Tract_N_DiagnosticAlta: TStringField;
    Tract_Comodin: TStringField;
    Tract_DiaFixe: TDateTimeField;
    Tract_C_LLit: TStringField;
    Tract_C_Planta: TStringField;
    Tract_Vegada: TSmallintField;
    Tract_C_CentreFac: TStringField;
    Tract_C_Client: TStringField;
    Tract_C_Delegacio: TStringField;
    Tract_CaducaPermis: TDateTimeField;
    Tract_PercentatgePacient: TFloatField;
    Tract_Referencia: TStringField;
    Tract_C_Infermeria: TStringField;
    Tract_C_Auxiliar: TStringField;
    Tract_C_Psicoleg: TStringField;
    Tract_C_TrevallSocial: TStringField;
    Tract_EsProvisional: TSmallintField;
    Tract_C_MetgePassi: TStringField;
    Tract_Passi: TStringField;
    Tract_Ambulancia: TStringField;
    Tract_C_EstatFac: TSmallintField;
    Tract_C_EsperaProgramada: TIntegerField;
    Tract_C_Stock: TSmallintField;
    Tract_confirmstock: TStringField;
    Tract_C_InfermeraPassi: TStringField;
    Tract_NotaCarrec: TIntegerField;
    Tract_NovaNotaCarrec: TStringField;
    Tract_C_EquipAssist: TIntegerField;
    Tract_c_logopeda: TStringField;
    Tract_C_Metge_InfAlta: TStringField;
    Tract_C_Proces: TIntegerField;
    Tract_Fi_Proces: TStringField;
    Tract_Metge_Proces: TStringField;
    Tract_C_Codi_E2: TStringField;
    Tract_N_Codi_E2: TStringField;
    Tract_C_Codi_E3: TStringField;
    Tract_N_Codi_E3: TStringField;
    Tract_Data_Sinistre: TDateTimeField;
    Tract_Matricula_Vehicle: TStringField;
    Tract_SIFCO: TStringField;
    Tract_FISS: TStringField;
    Tract_C_Codi_E4: TStringField;
    Tract_N_Codi_E4: TStringField;
    Tract_C_Codi_E5: TStringField;
    Tract_N_Codi_E5: TStringField;
    fPrestacio: THYEditFiltro;
    fDataAlta: THYEditFiltro;
    fCoordinador: THYEditFiltro;
    fProces: THYEditFiltro;
    Ed_Tract_C_InfermeraPassi: THYEdit;
    Tract_G_DiagnosticIngres: TStringField;
    Tract_G_DiagnosticAlta: TStringField;
    Ed_Tract_G_DiagnosticIngres: THYEdit;
    Ed_Tract_G_DiagnosticAlta: THYEdit;
    Eti_Tract_IcdIngres_N_ICD: THYLabel;
    Eti_Tract_IcdAlta_N_ICD: THYLabel;
    DiagI_G_Diagnostic: TStringField;
    DiagP_G_Diagnostic: TStringField;
    DiagA_G_Diagnostic: TStringField;
    Procediments: THYSqlBrowse;
    Procediments_C_Tractament: TIntegerField;
    Procediments_Tipus: TStringField;
    Procediments_Ordre: TSmallintField;
    Procediments_C_Metge: TStringField;
    Procediments_Data: TDateTimeField;
    dsProcediments: TDataSource;
    Procediments_C_Procediment: TStringField;
    Procediments_G_Procediment: TStringField;
    Procediments_N_Procediment: TStringField;
    TabDeficits: TTabSheet;
    Panel6: TPanel;
    Splitter3: TSplitter;
    Splitter2: TSplitter;
    Panel7: TPanel;
    HYGrid6: THYGrid;
    HYBarra8: THYBarra;
    Panel8: TPanel;
    HYGrid3: THYGrid;
    HYBarra5: THYBarra;
    Panel10: TPanel;
    HYBarra6: THYBarra;
    HYGrid4: THYGrid;
    Shape1: TShape;
    Ed_Tract_SIFCO: THYEdit;
    Ed_Tract_FISS: THYEdit;
    Tract_N_RESIDENCIA: TStringField;
    Tract_ACTUA_PADES: TStringField;
    Tract_hccc_informe_alta: TStringField;
    Tract_G_CODI_E: TStringField;
    Tract_G_CODI_E2: TStringField;
    Tract_G_CODI_E3: TStringField;
    Tract_G_CODI_E4: TStringField;
    Tract_G_CODI_E5: TStringField;
    DiagI_Classe: TStringField;
    DiagP_Classe: TStringField;
    DiagA_Classe: TStringField;
    tabSheet11: TTabSheet;
    Panel1: TPanel;
    HYGrid7: THYGrid;
    HYBarra9: THYBarra;
    Splitter6: TSplitter;
    HYArea4: THYArea;
    Eti_Tract_NumCas_N_CodiTract: THYLabel;
    Eti_Tract_ProcesOrigen_N_CodiTract: THYLabel;
    Ed_Tract_C_Cas: THYEdit;
    Ed_Tract_Complicacions: THYEdit;
    Ed_Tract_C_ProcesOrigen: THYEdit;
    Ed_Tract_Frankel: THYEdit;
    Ed_Tract_C_Codi_E: THYEdit;
    Ed_Tract_N_Codi_E: THYEdit;
    Ed_Tract_C_Codi_E2: THYEdit;
    Ed_Tract_N_Codi_E2: THYEdit;
    Ed_Tract_C_Codi_E3: THYEdit;
    Ed_Tract_N_Codi_E3: THYEdit;
    Ed_Tract_C_Codi_E4: THYEdit;
    Ed_Tract_N_Codi_E4: THYEdit;
    Ed_Tract_C_Codi_E5: THYEdit;
    Ed_Tract_N_Codi_E5: THYEdit;
    Ed_Tract_G_CODI_E: THYEdit;
    Ed_Tract_G_CODI_E2: THYEdit;
    Ed_Tract_G_CODI_E3: THYEdit;
    Ed_Tract_G_CODI_E4: THYEdit;
    Ed_Tract_G_CODI_E5: THYEdit;
    Label5: TLabel;
    Label6: TLabel;
    Label7: TLabel;
    Ed_Fili_C_Codi_E: THYEdit;
    Ed_Fili_N_Codi_E: THYEdit;
    Ed_Fili_C_Codi_E2: THYEdit;
    Ed_Fili_N_Codi_E2: THYEdit;
    HYBarra10: THYBarra;
    Fili: THYSqlBrowse;
    Fili_C_ORIGEN: TSmallintField;
    Fili_Frankel: TStringField;
    Fili_C_Codi_E: TStringField;
    Fili_N_Codi_E: TStringField;
    Fili_Comodin: TStringField;
    Fili_C_Codi_E2: TStringField;
    Fili_N_Codi_E2: TStringField;
    Fili_NUM_HIST: TIntegerField;
    Fili_APELLIDO1: TStringField;
    Fili_APELLIDO2: TStringField;
    Fili_NOMBRE: TStringField;
    Fili_NomComplet: TStringField;
    Fili_DNI: TStringField;
    Fili_NOMVIA: TStringField;
    Fili_ADRESA: TStringField;
    Fili_TELEFONO: TStringField;
    Fili_email: TStringField;
    Fili_TIPUSVIA: TStringField;
    Fili_CODIGO: TStringField;
    Fili_NUMERO: TStringField;
    Fili_BLOC: TStringField;
    Fili_ESCALA: TStringField;
    Fili_PIS: TStringField;
    Fili_PORTA: TStringField;
    Fili_POBLACIO: TStringField;
    Fili_PROVINCIA: TStringField;
    Fili_RESIDENCIA: TStringField;
    Fili_PAIS: TStringField;
    Fili_SEXO: TStringField;
    Fili_FECHA_NAC: TDateTimeField;
    Fili_LUGAR_NAC: TStringField;
    Fili_ESTADO_CIV: TStringField;
    Fili_SOE: TStringField;
    Fili_TSI: TStringField;
    Fili_TITULAR: TStringField;
    Fili_PENSIONIST: TStringField;
    Fili_IDIOMA: TSmallintField;
    Fili_TELEFO1_FAM: TStringField;
    Fili_DESCRIPCIO1: TStringField;
    Fili_TELEFO2_FAM: TStringField;
    Fili_DESCRIPCIO2: TStringField;
    Fili_AMIC: TFloatField;
    Fili_MORT: TDateTimeField;
    Fili_EsViu: TStringField;
    Fili_Edat: TIntegerField;
    Fili_USRA: TIntegerField;
    Fili_UNITAT: TSmallintField;
    Fili_C_UnitatMedica: TSmallintField;
    Fili_Bloqueig: TStringField;
    Fili_Objectius: TIntegerField;
    Fili_C_Etiologia: TStringField;
    Fili_N_Etiologia: TStringField;
    Fili_Data_Lessio: TDateTimeField;
    Fili_C_ClasAnat: TSmallintField;
    Fili_C_FracturaVertebral: TSmallintField;
    Fili_c_TipusBufeta: TSmallintField;
    Fili_C_Bipedestacio: TSmallintField;
    Fili_C_InfeccioUrinaria: TSmallintField;
    Fili_C_Disreflexia: TSmallintField;
    Fili_C_Cadira: TSmallintField;
    Fili_C_FuncioSexual: TSmallintField;
    Fili_C_Ereccio: TSmallintField;
    Fili_C_Ejaculacio: TSmallintField;
    Fili_C_Semen: TSmallintField;
    Fili_C_TractamentOrtopedic: TSmallintField;
    Fili_C_Deambulacio: TSmallintField;
    Fili_C_Bitutors: TSmallintField;
    Fili_C_Ajudes: TSmallintField;
    Fili_C_DrenatgeUrinari: TSmallintField;
    Fili_Alergies: TStringField;
    Fili_Data_Contacte: TDateTimeField;
    Fili_Data_UltimContacte: TDateTimeField;
    Fili_Ultima1: TDateTimeField;
    Fili_AnticsTractaments: TMemoField;
    Fili_C_DIAGNOSTICNEUROLOGIC: TStringField;
    Fili_N_DIAGNOSTICNEUROLOGIC: TStringField;
    Fili_C_Dieta: TSmallintField;
    Fili_Obs_Dieta: TStringField;
    Fili_CONSENTIMENT: TStringField;
    Fili_Voluntats: TStringField;
    Fili_ConsentimentInf: TStringField;
    Fili_Donant: TStringField;
    Fili_RCP: TStringField;
    Fili_Glasgow: TSmallintField;
    Fili_PesCadira: TFloatField;
    Fili_NIHSS: TSmallintField;
    Fili_C_CAUSA: TSmallintField;
    Fili_C_Causa_Detall: TSmallintField;
    Fili_CAUSA_ALTRES: TStringField;
    Fili_UM_ANTIGA: TSmallintField;
    Fili_Dies_APT: TIntegerField;
    Fili_Previrnec: TIntegerField;
    Fili_c_Lateralitat: TSmallintField;
    Fili_G_DeficitNeurologic: TStringField;
    Fili_G_EfecteTarda: TStringField;
    Fili_Incapacitat: TStringField;
    Fili_Incapacitat_Tutor: TStringField;
    Fili_Incapacitat_Telefon: TStringField;
    Fili_LleiDEP: TSmallintField;
    Fili_RIC: TStringField;
    Fili_GLF: TStringField;
    Fili_C_HOSPITAL: TSmallintField;
    dsFili: TDataSource;
    Splitter7: TSplitter;
    Splitter8: TSplitter;
    DiagA_OrdreCMB: TSmallintField;
    DiagA_ClasseCMB: TStringField;
    DiagP_OrdreCMB: TSmallintField;
    DiagP_ClasseCMB: TStringField;
    DiagI_POA: TStringField;
    DiagI_OrdreCMB: TSmallintField;
    DiagI_ClasseCMB: TStringField;
    DiagI_POACMB: TStringField;
    DiagP_POA: TStringField;
    DiagP_POACMB: TStringField;
    DiagA_POA: TStringField;
    DiagA_POACMB: TStringField;
    Ed_Tract_hccc_informe_alta: THYEdit;
    HYEdit1: THYEdit;
    Tract_hccc_infalta_infer: TStringField;
    Tract_PM: TFloatField;
    Tract_PMDRG: TFloatField;
    HYEdit2: THYEdit;
    HYEdit3: THYEdit;
    Fili_C_EXITUS: TStringField;
    Fili_MR: TStringField;
    Fili_T_DOC: TStringField;
    Fili_CRITIC: TStringField;
    Fili_Severitat: TSmallintField;
    Fili_Correspondencia: TStringField;
    Fili_Impagat: TStringField;
    Fili_SNS: TStringField;
    Tract_Hora_Alta: TStringField;
    Tract_c_fisio_labo_marxa: TStringField;
    Tract_c_fisio_ar: TStringField;
    bProces: THYSqlBrowse;
    bProces_C_Proces: TIntegerField;
    bProces_C_Historia: TIntegerField;
    bProces_Data_inici: TDateTimeField;
    dsProces: TDataSource;
    TabAmbulatori: TTabSheet;
    HYArea5: THYArea;
    Eti_Tract_Frequencia_DESCRIPCIO: THYLabel;
    Eti_Tract_Fisioterapeuta_Metge: THYLabel;
    Eti_Tract_Terapeuta_Metge: THYLabel;
    Label1: TLabel;
    Ed_Tract_C_Frequencia: THYEdit;
    Ed_Tract_DiaFixe: THYEdit;
    Ed_Tract_C_FisioTerapeuta: THYEdit;
    Ed_Tract_C_Terapeuta: THYEdit;
    Ed_Tract_C_Infermeria: THYEdit;
    Ed_Tract_C_Auxiliar: THYEdit;
    Ed_Tract_C_Psicoleg: THYEdit;
    Ed_Tract_C_TrevallSocial: THYEdit;
    Ed_Tract_C_LOGOPEDA: THYEdit;
    Panel17: TPanel;
    DBNavigator3: TDBNavigator;
    HYEdit4: THYEdit;
    HYEdit5: THYEdit;
    bPautes: THYSqlBrowse;
    bPautes_C_Proces: TIntegerField;
    bPautes_Data_Inici: TDateTimeField;
    dsPautes: TDataSource;
    bTorns: THYSqlBrowse;
    bTorns_C_Proces: TIntegerField;
    dsTorns: TDataSource;
    Panel18: TPanel;
    HYBarra11: THYBarra;
    Panel19: TPanel;
    HYGrid8: THYGrid;
    bPautes_ID: TIntegerField;
    bPautes_C_Tractament: TIntegerField;
    bPautes_Data_Prealta: TDateTimeField;
    bPautes_Dies_Extra: TIntegerField;
    bPautes_Setmanes_5D: TSmallintField;
    bPautes_Setmanes_3D: TSmallintField;
    bPautes_C_Motiu: TSmallintField;
    bPautes_Comentari: TStringField;
    bPautes_Estat: TStringField;
    bPautes_C_Usuari: TStringField;
    bPautes_Data: TDateTimeField;
    bPautes_C_Usuari_Susp: TStringField;
    bPautes_Data_Susp: TDateTimeField;
    bTorns_Dia_Inici: TDateTimeField;
    bTorns_Frequencia: TSmallintField;
    bTorns_Torn: TStringField;
    bTorns_C_Usuari: TStringField;
    bTorns_Data: TDateTimeField;
    HYArea11: THYArea;
    Ed_bPautes_C_Proces: THYEdit;
    Ed_bPautes_Data_inici: THYEdit;
    Ed_bPautes_ID: THYEdit;
    Ed_bPautes_C_Tractament: THYEdit;
    Ed_bPautes_Data_Prealta: THYEdit;
    Ed_bPautes_Dies_Extra: THYEdit;
    Ed_bPautes_Setmanes_5D: THYEdit;
    Ed_bPautes_Setmanes_3D: THYEdit;
    Ed_bPautes_C_Motiu: THYEdit;
    Ed_bPautes_Comentari: THYEdit;
    Ed_bPautes_Estat: THYEdit;
    Ed_bPautes_C_Usuari: THYEdit;
    Ed_bPautes_Data: THYEdit;
    Ed_bPautes_C_Usuari_Susp: THYEdit;
    Ed_bPautes_Data_Susp: THYEdit;
    Eti_bPautes_metges_Metge: THYLabel;
    Eti_bPautes_metges2_Metge: THYLabel;
    Eti_bPautes_motiu_N_Codi: THYLabel;
    Eti_Tract_Motiu_N_Codi: THYLabel;
    HYBarra4: THYBarra;
    HYGrid9: THYGrid;
    HYEdit6: THYEdit;
    Fili_PAIS_NAIX: TStringField;
    Tract_Data_fi_contractat: TDateTimeField;
    Tract_Data_no_renovacio: TDateTimeField;
    Procediments_Dispositiu: TStringField;
    Tract_DESTI_CONT_EXT: TSmallintField;
    Tract_DESTI_CONT_INT: TSmallintField;
    Tract_BECA: TFloatField;
    Ed_Tract_BECA: THYEdit;
    Ed_Tract_Hora_Alta: THYEdit;
    Ed_Tract_DESTI_CONT_EXT: THYEdit;
    Ed_Tract_DESTI_CONT_INT: THYEdit;
    Eti_Tract_DESTI_CONT_EXT_N_Codi: THYLabel;
    Eti_Tract_DESTI_CONT_INT_N_Codi: THYLabel;
    Ed_Tract_c_fisio_ar: THYEdit;
    Ed_Tract_c_fisio_labo_marxa: THYEdit;
    Ed_Tract_Data_fi_contractat: THYEdit;
    Ed_Tract_Data_no_renovacio: THYEdit;
    Fili_Nivell_cobertura: TSmallintField;
    Fili_CCAA: TStringField;
    Fili_PAIS_DOC: TStringField;
    Tract_C_MUSICOTERAPEUTA: TStringField;
    Tract_CMBD_AEA: TStringField;
    Tract_REPUBLICAR_HC3: TStringField;
    Eti_Tract_HtalOrigen_C_UP: THYLabel;
    Eti_Tract_HtalDestinacio_C_UP: THYLabel;
    Label2: TLabel;
    Label3: TLabel;
    Fili_SMS: TStringField;
    Fili_REVISTA: TStringField;
    Eti_Tract_DESTI_CONT_EXT_R_Codi: THYLabel;
    Eti_Tract_DESTI_CONT_INT_R_Codi: THYLabel;
    Label4: TLabel;
    Tract_T_HABITACIO: TSmallintField;
    Tract_ID_GARANT: TIntegerField;
    Tract_PRESSUPOST: TStringField;
    Tract_T_SESSIO: TSmallintField;
    Tract_ID_FACILITADOR: TIntegerField;
    Ed_Tract_T_HABITACIO: THYEdit;
    Ed_Tract_ID_GARANT: THYEdit;
    Ed_Tract_PRESSUPOST: THYEdit;
    Ed_Tract_T_SESSIO: THYEdit;
    Ed_Tract_ID_FACILITADOR: THYEdit;
    Eti_Tract_TipHab_N_Codi: THYLabel;
    Eti_Tract_Garant_COGNOM1: THYLabel;
    Eti_Tract_Garant_COGNOM2: THYLabel;
    Eti_Tract_Garant_NOM: THYLabel;
    Eti_Tract_TSessio_N_Codi: THYLabel;
    Eti_Tract_Facilitador_COGNOM1: THYLabel;
    Eti_Tract_Facilitador_COGNOM2: THYLabel;
    Eti_Tract_Facilitador_NOM: THYLabel;
    Ed_Tract_C_MUSICOTERAPEUTA: THYEdit;
    Tract_UCI: TStringField;
    Tract_METGE_MUTUA: TStringField;
    Tract_TELF_METGE_MUTUA: TStringField;
    Tract_VersioCIM: TIntegerField;
    DiagI_VersioCIM: TIntegerField;
    DiagP_VersioCIM: TIntegerField;
    Procediments_VersioCIM: TIntegerField;
    DeficitsA_C0_0: TStringField;
    DeficitsA_C0_1: TStringField;
    DeficitsA_C0_2: TStringField;
    DeficitsA_C0_3: TStringField;
    DeficitsA_C0_4: TStringField;
    DeficitsA_C0_5: TStringField;
    DeficitsA_C1_0: TSmallintField;
    DeficitsA_C1_1: TStringField;
    DeficitsA_C1_2: TSmallintField;
    DeficitsA_C1_3: TStringField;
    DeficitsA_C1_4: TStringField;
    DeficitsP_C0_0: TStringField;
    DeficitsP_C0_1: TStringField;
    DeficitsP_C0_2: TStringField;
    DeficitsP_C0_3: TStringField;
    DeficitsP_C0_4: TStringField;
    DeficitsP_C0_5: TStringField;
    DeficitsP_C1_0: TSmallintField;
    DeficitsP_C1_1: TStringField;
    DeficitsP_C1_2: TSmallintField;
    DeficitsP_C1_3: TStringField;
    DeficitsP_C1_4: TStringField;
    DeficitsI_C0_0: TStringField;
    DeficitsI_C0_1: TStringField;
    DeficitsI_C0_2: TStringField;
    DeficitsI_C0_3: TStringField;
    DeficitsI_C0_4: TStringField;
    DeficitsI_C0_5: TStringField;
    DeficitsI_C1_0: TSmallintField;
    DeficitsI_C1_1: TStringField;
    DeficitsI_C1_2: TSmallintField;
    DeficitsI_C1_3: TStringField;
    DeficitsI_C1_4: TStringField;
    DiagA_VersioCIM: TIntegerField;
    Fili_LMS_Activitat: TDateTimeField;
    Fili_RISC_SUICIDI: TStringField;
    Fili_LMS_REGISTRE: TIntegerField;
    Fili_VersioCIM: TIntegerField;
    Ed_Tract_VersioCIM: THYEdit;
    HYEdit7: THYEdit;
    Tract_VersioCIM_G: TIntegerField;
    DiagI_VersioCIM_G: TIntegerField;
    DiagP_VersioCIM_G: TIntegerField;
    DiagP_C0_0: TStringField;
    DiagP_C0_1: TStringField;
    DiagP_C0_2: TStringField;
    DiagP_C0_3: TStringField;
    DiagP_C0_4: TStringField;
    DiagP_C0_5: TStringField;
    DiagP_C0_6: TStringField;
    DiagP_C0_7: TStringField;
    DiagP_C0_8: TStringField;
    DiagP_C0_9: TStringField;
    DiagP_C0_10: TSmallintField;
    DiagP_C0_11: TStringField;
    DiagP_C0_12: TStringField;
    DiagP_C0_13: TStringField;
    DiagP_C0_14: TStringField;
    DiagP_C0_15: TStringField;
    DiagP_C0_16: TStringField;
    DiagP_C0_17: TIntegerField;
    DiagP_C1_0: TStringField;
    DiagP_C1_1: TStringField;
    DiagP_C1_2: TStringField;
    DiagP_C1_3: TStringField;
    DiagP_C1_4: TStringField;
    DiagP_C1_5: TStringField;
    DiagP_C1_6: TStringField;
    DiagP_C1_7: TStringField;
    DiagP_C1_8: TStringField;
    DiagP_C1_9: TStringField;
    DiagP_C1_10: TSmallintField;
    DiagP_C1_11: TStringField;
    DiagP_C1_12: TStringField;
    DiagP_C1_13: TStringField;
    DiagP_C1_14: TStringField;
    DiagP_C1_15: TStringField;
    DiagP_C1_16: TStringField;
    DiagP_C1_17: TIntegerField;
    DiagP_C2_0: TStringField;
    DiagP_C2_1: TStringField;
    DiagP_C3_0: TStringField;
    DiagP_C3_1: TStringField;
    DiagP_C4_0: TStringField;
    DiagP_C4_1: TStringField;
    DiagP_C5_0: TStringField;
    DiagP_C5_1: TStringField;
    DiagA_VersioCIM_G: TIntegerField;
    DiagA_C0_0: TStringField;
    DiagA_C0_1: TStringField;
    DiagA_C0_2: TStringField;
    DiagA_C0_3: TStringField;
    DiagA_C0_4: TStringField;
    DiagA_C0_5: TStringField;
    DiagA_C0_6: TStringField;
    DiagA_C0_7: TStringField;
    DiagA_C0_8: TStringField;
    DiagA_C0_9: TStringField;
    DiagA_C0_10: TSmallintField;
    DiagA_C0_11: TStringField;
    DiagA_C0_12: TStringField;
    DiagA_C0_13: TStringField;
    DiagA_C0_14: TStringField;
    DiagA_C0_15: TStringField;
    DiagA_C0_16: TStringField;
    DiagA_C0_17: TIntegerField;
    DiagA_C1_0: TStringField;
    DiagA_C1_1: TStringField;
    DiagA_C1_2: TStringField;
    DiagA_C1_3: TStringField;
    DiagA_C1_4: TStringField;
    DiagA_C1_5: TStringField;
    DiagA_C1_6: TStringField;
    DiagA_C1_7: TStringField;
    DiagA_C1_8: TStringField;
    DiagA_C1_9: TStringField;
    DiagA_C1_10: TSmallintField;
    DiagA_C1_11: TStringField;
    DiagA_C1_12: TStringField;
    DiagA_C1_13: TStringField;
    DiagA_C1_14: TStringField;
    DiagA_C1_15: TStringField;
    DiagA_C1_16: TStringField;
    DiagA_C1_17: TIntegerField;
    DiagA_C2_0: TStringField;
    DiagA_C2_1: TStringField;
    DiagA_C3_0: TStringField;
    DiagA_C3_1: TStringField;
    DiagA_C4_0: TStringField;
    DiagA_C4_1: TStringField;
    DiagA_C5_0: TStringField;
    DiagA_C5_1: TStringField;
    Procediments_VersioCIM_G: TIntegerField;
    Procediments_C0_0: TStringField;
    Procediments_C0_1: TStringField;
    Procediments_C0_2: TStringField;
    Procediments_C0_3: TStringField;
    Procediments_C0_4: TStringField;
    Procediments_C0_5: TStringField;
    Procediments_C0_6: TStringField;
    Procediments_C0_7: TStringField;
    Procediments_C0_8: TStringField;
    Procediments_C0_9: TStringField;
    Procediments_C0_10: TSmallintField;
    Procediments_C0_11: TStringField;
    Procediments_C0_12: TStringField;
    Procediments_C0_13: TStringField;
    Procediments_C0_14: TStringField;
    Procediments_C0_15: TStringField;
    Procediments_C0_16: TStringField;
    Procediments_C0_17: TIntegerField;
    Procediments_C1_0: TStringField;
    Procediments_C1_1: TStringField;
    Procediments_C1_2: TStringField;
    Procediments_C1_3: TStringField;
    Procediments_C1_4: TStringField;
    Procediments_C1_5: TStringField;
    Procediments_C1_6: TStringField;
    Procediments_C1_7: TStringField;
    Procediments_C1_8: TStringField;
    Procediments_C1_9: TStringField;
    Procediments_C1_10: TSmallintField;
    Procediments_C1_11: TStringField;
    Procediments_C1_12: TStringField;
    Procediments_C1_13: TStringField;
    Procediments_C1_14: TStringField;
    Procediments_C1_15: TStringField;
    Procediments_C1_16: TStringField;
    Procediments_C1_17: TIntegerField;
    Procediments_C2_0: TStringField;
    Procediments_C2_1: TStringField;
    Procediments_C2_2: TStringField;
    Procediments_C2_3: TStringField;
    Fili_VersioCIM_G: TIntegerField;
    HYEdit8: THYEdit;
    Tract_Publicacio_CMDB: TStringField;
    Tract_ConfiancaDPI: TFloatField;
    Tract_ConfiancaDPA: TFloatField;
    Tract_ID_DPI: TStringField;
    Tract_ID_DPA: TStringField;
    Ed_Tract_ConfiancaDPA: THYEdit;
    Ed_Tract_ID_DPA: THYEdit;
    Ed_Tract_ConfiancaDPI: THYEdit;
    Ed_Tract_ID_DPI: THYEdit;
    Eti_Tract_IcdAlta_RIC: THYLabel;
    Eti_Tract_IcdAlta_GLF: THYLabel;
    TractCodificacio: THYSqlBrowse;
    dsTractCodificacio: TDataSource;
    HYArea10: THYArea;
    TractCodificacio_C_TRACTAMENT: TIntegerField;
    TractCodificacio_GRD: TIntegerField;
    TractCodificacio_NivellSeveritat: TIntegerField;
    TractCodificacio_Pes: TStringField;
    TractCodificacio_RiscMortalitat: TIntegerField;
    TractCodificacio_CDM: TIntegerField;
    TractCodificacio_C0_0: TIntegerField;
    TractCodificacio_C0_1: TIntegerField;
    TractCodificacio_C0_2: TStringField;
    TractCodificacio_C0_3: TDateTimeField;
    TractCodificacio_C0_4: TDateTimeField;
    TractCodificacio_C0_5: TDateTimeField;
    TractCodificacio_C0_6: TStringField;
    TractCodificacio_C0_7: TStringField;
    TractCodificacio_C0_8: TStringField;
    TractCodificacio_C0_9: TFloatField;
    TractCodificacio_C0_10: TStringField;
    TractCodificacio_C0_11: TStringField;
    TractCodificacio_C0_12: TStringField;
    TractCodificacio_C0_13: TStringField;
    TractCodificacio_C0_14: TSmallintField;
    TractCodificacio_C0_15: TSmallintField;
    TractCodificacio_C0_16: TSmallintField;
    TractCodificacio_C0_17: TStringField;
    TractCodificacio_C0_18: TStringField;
    TractCodificacio_C0_19: TStringField;
    TractCodificacio_C0_20: TIntegerField;
    TractCodificacio_C0_21: TStringField;
    TractCodificacio_C0_22: TStringField;
    TractCodificacio_C0_23: TStringField;
    TractCodificacio_C0_24: TStringField;
    TractCodificacio_C0_25: TStringField;
    TractCodificacio_C0_26: TStringField;
    TractCodificacio_C0_27: TStringField;
    TractCodificacio_C0_28: TDateTimeField;
    TractCodificacio_C0_29: TIntegerField;
    Ed_TractCodificacio_GRD: THYEdit;
    Ed_TractCodificacio_NivellSeveritat: THYEdit;
    Ed_TractCodificacio_Pes: THYEdit;
    Ed_TractCodificacio_RiscMortalitat: THYEdit;
    Ed_TractCodificacio_CDM: THYEdit;
    HYBarra12: THYBarra;
    Splitter9: TSplitter;
    DiagI_CONFIANCA: TFloatField;
    DiagI_ID_DIAGNOSTIC: TStringField;
    DiagI_C0_0: TStringField;
    DiagI_C0_1: TStringField;
    DiagI_C0_2: TStringField;
    DiagI_C0_3: TStringField;
    DiagI_C0_4: TStringField;
    DiagI_C0_5: TStringField;
    DiagI_C0_6: TStringField;
    DiagI_C0_7: TStringField;
    DiagI_C0_8: TStringField;
    DiagI_C0_9: TStringField;
    DiagI_C0_10: TSmallintField;
    DiagI_C0_11: TStringField;
    DiagI_C0_12: TStringField;
    DiagI_C0_13: TStringField;
    DiagI_C0_14: TStringField;
    DiagI_C0_15: TStringField;
    DiagI_C0_16: TStringField;
    DiagI_C0_17: TIntegerField;
    DiagI_C1_0: TStringField;
    DiagI_C1_1: TStringField;
    DiagI_C1_2: TStringField;
    DiagI_C1_3: TStringField;
    DiagI_C1_4: TStringField;
    DiagI_C1_5: TStringField;
    DiagI_C1_6: TStringField;
    DiagI_C1_7: TStringField;
    DiagI_C1_8: TStringField;
    DiagI_C1_9: TStringField;
    DiagI_C1_10: TSmallintField;
    DiagI_C1_11: TStringField;
    DiagI_C1_12: TStringField;
    DiagI_C1_13: TStringField;
    DiagI_C1_14: TStringField;
    DiagI_C1_15: TStringField;
    DiagI_C1_16: TStringField;
    DiagI_C1_17: TIntegerField;
    DiagI_C2_0: TStringField;
    DiagI_C2_1: TStringField;
    DiagI_C3_0: TStringField;
    DiagI_C3_1: TStringField;
    DiagI_C4_0: TStringField;
    DiagI_C4_1: TStringField;
    DiagI_C5_0: TStringField;
    DiagI_C5_1: TStringField;
    Tract_CADA_X_SETMANES: TIntegerField;
    Tract_Motiu_Dia_Prealta: TStringField;
    Tract_Motiu_Canvi_Prealta: TStringField;
    Tract_C_Terapeuta_Resp: TStringField;
    Tract_Obs_Secre: TStringField;
    Tract_Codificat_Revisat: TStringField;
    TabSheet3: TTabSheet;
    tPermisos: THYSqlBrowse;
    tPermisosLog: THYSqlBrowse;
    HYBarra13: THYBarra;
    dsPermisos: TDataSource;
    dsPermisosLog: TDataSource;
    tPermisos_c_permis: TIntegerField;
    tPermisos_C_Tractament: TIntegerField;
    tPermisos_C_Estat: TStringField;
    tPermisos_Tipus: TStringField;
    tPermisos_Motiu: TStringField;
    tPermisos_Autoritzacio: TStringField;
    tPermisos_Ausencia: TStringField;
    tPermisosLog_c_log: TIntegerField;
    tPermisosLog_C_Permis: TIntegerField;
    tPermisosLog_c_accio: TStringField;
    tPermisosLog_c_usuari: TStringField;
    tPermisosLog_data: TDateTimeField;
    tPermisosLog_hora: TStringField;
    tPermisosLog_Observacions: TStringField;
    HYGrid10: THYGrid;
    Panel20: TPanel;
    HYBarra14: THYBarra;
    HYGrid11: THYGrid;
    tPermisos_data_permis: TDateTimeField;
    tPermisos_hora_permis: TStringField;
    Tract_C_FREQUENCIA_TIPUS: TSmallintField;
    Tract_HORA_INI_REHAB: TStringField;
    Tract_HORA_FIN_REHAB: TStringField;
    Fili_Hora_Dinar: TStringField;
    Fili_C_Ubicacio_Dinar: TSmallintField;
    Fili_Autoritza_llit: TStringField;
    Fili_Autoritza_enquestes: TStringField;
    Fili_Autoritza_investigacio: TStringField;
    tPermisos_Permanent: TStringField;
    tPermisos_Horaentrada: TSmallintField;
    tPermisos_C0_0: TIntegerField;
    tPermisos_C0_1: TIntegerField;
    tPermisos_C0_2: TStringField;
    tPermisos_C0_3: TDateTimeField;
    tPermisos_C0_4: TDateTimeField;
    tPermisos_C0_5: TDateTimeField;
    tPermisos_C0_6: TStringField;
    tPermisos_C0_7: TStringField;
    tPermisos_C0_8: TStringField;
    tPermisos_C0_9: TFloatField;
    tPermisos_C0_10: TStringField;
    tPermisos_C0_11: TStringField;
    tPermisos_C0_12: TStringField;
    tPermisos_C0_13: TStringField;
    tPermisos_C0_14: TSmallintField;
    tPermisos_C0_15: TSmallintField;
    tPermisos_C0_16: TSmallintField;
    tPermisos_C0_17: TStringField;
    tPermisos_C0_18: TStringField;
    tPermisos_C0_19: TStringField;
    tPermisos_C0_20: TIntegerField;
    tPermisos_C0_21: TStringField;
    tPermisos_C0_22: TStringField;
    tPermisos_C0_23: TStringField;
    tPermisos_C0_24: TStringField;
    tPermisos_C0_25: TStringField;
    tPermisos_C0_26: TStringField;
    tPermisos_C0_27: TStringField;
    tPermisos_C0_28: TDateTimeField;
    tPermisos_C0_29: TIntegerField;
    tPermisos_C1_0: TStringField;
    tPermisos_C1_1: TStringField;
    tPermisos_C2_0: TStringField;
    tPermisos_C2_1: TStringField;
    tPermisosLog_C0_0: TStringField;
    tPermisosLog_C0_1: TStringField;
    tPermisosLog_C0_2: TStringField;
    tPermisosLog_C0_3: TStringField;
    tPermisosLog_C0_4: TStringField;
    tPermisosLog_C0_5: TStringField;
    tPermisosLog_C0_6: TStringField;
    tPermisosLog_C0_7: TIntegerField;
    tPermisosLog_C0_8: TStringField;
    tPermisosLog_C0_9: TStringField;
    tPermisosLog_C0_10: TSmallintField;
    tPermisosLog_C0_11: TStringField;
    tPermisosLog_C0_12: TStringField;
    tPermisosLog_C0_13: TStringField;
    tPermisosLog_C0_14: TStringField;
    tPermisosLog_C1_0: TIntegerField;
    tPermisosLog_C1_1: TIntegerField;
    tPermisosLog_C1_2: TStringField;
    tPermisosLog_C1_3: TStringField;
    tPermisosLog_C1_4: TStringField;
    tPermisosLog_C1_5: TStringField;
    tPermisosLog_C1_6: TStringField;
    tPermisosLog_C2_0: TStringField;
    tPermisosLog_C2_1: TStringField;
    Eti_Tract_EstatFac_N_Codi: THYLabel;
    Eti_Tract_EstatFac_R_Codi: THYLabel;
    Ed_Tract_EsProvisional: THYCheck;
    Tract_DiesConsumits: TIntegerField;
    Fili_HCE_DEDUPE: TIntegerField;
    Fili_C0_0: TStringField;
    Fili_C0_1: TStringField;
    Fili_C0_2: TStringField;
    Fili_C1_0: TStringField;
    Fili_C1_1: TStringField;
    Fili_C1_2: TStringField;
    Fili_C2_0: TStringField;
    Fili_C2_1: TStringField;
    Fili_C3_0: TSmallintField;
    Fili_C3_1: TStringField;
    Fili_C3_2: TSmallintField;
    Fili_C3_3: TStringField;
    Fili_C3_4: TStringField;
    Fili_C3_5: TStringField;
    Fili_C4_0: TIntegerField;
    Fili_C4_1: TIntegerField;
    Fili_C4_2: TStringField;
    Fili_C4_3: TStringField;
    Fili_C4_4: TStringField;
    Fili_C5_0: TSmallintField;
    Fili_C5_1: TStringField;
    Fili_C5_2: TSmallintField;
    Fili_C5_3: TStringField;
    Fili_C5_4: TStringField;
    Fili_C5_5: TStringField;
    Fili_C6_0: TSmallintField;
    Fili_C6_1: TStringField;
    Fili_C6_2: TSmallintField;
    Fili_C6_3: TStringField;
    Fili_C6_4: TStringField;
    Fili_C6_5: TStringField;
    Fili_C7_0: TSmallintField;
    Fili_C7_1: TStringField;
    Fili_C7_2: TSmallintField;
    Fili_C7_3: TStringField;
    Fili_C7_4: TStringField;
    Fili_C7_5: TStringField;
    Fili_C8_0: TSmallintField;
    Fili_C8_1: TStringField;
    Fili_C8_2: TSmallintField;
    Fili_C8_3: TStringField;
    Fili_C8_4: TStringField;
    Fili_C8_5: TStringField;
    Fili_C9_0: TSmallintField;
    Fili_C9_1: TStringField;
    Fili_C9_2: TSmallintField;
    Fili_C9_3: TStringField;
    Fili_C9_4: TStringField;
    Fili_C9_5: TStringField;
    Fili_C10_0: TSmallintField;
    Fili_C10_1: TStringField;
    Fili_C10_2: TSmallintField;
    Fili_C10_3: TStringField;
    Fili_C10_4: TStringField;
    Fili_C10_5: TStringField;
    Fili_C11_0: TSmallintField;
    Fili_C11_1: TStringField;
    Fili_C11_2: TSmallintField;
    Fili_C11_3: TStringField;
    Fili_C11_4: TStringField;
    Fili_C11_5: TStringField;
    Fili_C12_0: TSmallintField;
    Fili_C12_1: TStringField;
    Fili_C12_2: TSmallintField;
    Fili_C12_3: TStringField;
    Fili_C12_4: TStringField;
    Fili_C12_5: TStringField;
    Fili_C13_0: TSmallintField;
    Fili_C13_1: TStringField;
    Fili_C13_2: TSmallintField;
    Fili_C13_3: TStringField;
    Fili_C13_4: TStringField;
    Fili_C13_5: TStringField;
    Fili_C14_0: TSmallintField;
    Fili_C14_1: TStringField;
    Fili_C14_2: TSmallintField;
    Fili_C14_3: TStringField;
    Fili_C14_4: TStringField;
    Fili_C14_5: TStringField;
    Fili_C15_0: TSmallintField;
    Fili_C15_1: TStringField;
    Fili_C15_2: TSmallintField;
    Fili_C15_3: TStringField;
    Fili_C15_4: TStringField;
    Fili_C15_5: TStringField;
    Fili_C16_0: TSmallintField;
    Fili_C16_1: TStringField;
    Fili_C16_2: TSmallintField;
    Fili_C16_3: TStringField;
    Fili_C16_4: TStringField;
    Fili_C16_5: TStringField;
    Fili_C17_0: TSmallintField;
    Fili_C17_1: TStringField;
    Fili_C17_2: TSmallintField;
    Fili_C17_3: TStringField;
    Fili_C17_4: TStringField;
    Fili_C17_5: TStringField;
    Fili_C18_0: TSmallintField;
    Fili_C18_1: TStringField;
    Fili_C18_2: TSmallintField;
    Fili_C18_3: TStringField;
    Fili_C18_4: TStringField;
    Fili_C18_5: TStringField;
    Fili_C19_0: TSmallintField;
    Fili_C19_1: TStringField;
    Fili_C19_2: TSmallintField;
    Fili_C19_3: TStringField;
    Fili_C19_4: TStringField;
    Fili_C19_5: TStringField;
    Fili_C20_0: TSmallintField;
    Fili_C20_1: TStringField;
    Fili_C20_2: TSmallintField;
    Fili_C20_3: TStringField;
    Fili_C20_4: TStringField;
    Fili_C20_5: TStringField;
    Fili_C21_0: TSmallintField;
    Fili_C21_1: TStringField;
    Fili_C21_2: TSmallintField;
    Fili_C21_3: TStringField;
    Fili_C21_4: TStringField;
    Fili_C21_5: TStringField;
    Fili_C22_0: TStringField;
    Fili_C22_1: TStringField;
    Fili_C22_2: TStringField;
    Fili_C22_3: TStringField;
    Fili_C23_0: TStringField;
    Fili_C23_1: TStringField;
    Fili_C23_2: TStringField;
    Fili_C23_3: TStringField;
    Fili_C24_0: TStringField;
    Fili_C24_1: TStringField;
    Fili_C25_0: TSmallintField;
    Fili_C25_1: TStringField;
    Fili_C25_2: TSmallintField;
    Fili_C25_3: TStringField;
    Fili_C25_4: TStringField;
    Fili_C25_5: TStringField;
    Fili_C26_0: TSmallintField;
    Fili_C26_1: TStringField;
    Fili_C26_2: TSmallintField;
    Fili_C26_3: TSmallintField;
    Fili_C26_4: TStringField;
    Fili_C26_5: TStringField;
    Fili_C26_6: TSmallintField;
    Fili_C27_0: TSmallintField;
    Fili_C27_1: TStringField;
    Fili_C27_2: TSmallintField;
    Fili_C27_3: TStringField;
    Fili_C27_4: TStringField;
    Fili_C27_5: TStringField;
    Fili_C28_0: TSmallintField;
    Fili_C28_1: TStringField;
    Fili_C28_2: TSmallintField;
    Fili_C28_3: TStringField;
    Fili_C28_4: TStringField;
    Fili_C28_5: TStringField;
    Fili_C29_0: TSmallintField;
    Fili_C29_1: TStringField;
    Fili_C29_2: TSmallintField;
    Fili_C29_3: TStringField;
    Fili_C29_4: TStringField;
    Fili_C29_5: TStringField;
    Fili_C30_0: TSmallintField;
    Fili_C30_1: TStringField;
    Fili_C30_2: TSmallintField;
    Fili_C30_3: TStringField;
    Fili_C30_4: TStringField;
    Fili_C30_5: TStringField;
    Fili_C31_0: TSmallintField;
    Fili_C31_1: TStringField;
    Fili_C31_2: TSmallintField;
    Fili_C31_3: TStringField;
    Fili_C31_4: TStringField;
    Fili_C31_5: TStringField;
    Fili_C32_0: TStringField;
    Fili_C32_1: TStringField;
    Fili_C32_2: TStringField;
    Fili_C32_3: TStringField;
    Fili_C32_4: TStringField;
    Fili_C32_5: TStringField;
    Fili_C32_6: TStringField;
    Fili_C32_7: TStringField;
    Fili_C32_8: TStringField;
    Fili_C32_9: TStringField;
    Fili_C32_10: TSmallintField;
    Fili_C32_11: TStringField;
    Fili_C32_12: TStringField;
    Fili_C32_13: TStringField;
    Fili_C32_14: TStringField;
    Fili_C32_15: TStringField;
    Fili_C32_16: TStringField;
    Fili_C32_17: TIntegerField;
    Fili_C33_0: TStringField;
    Fili_C33_1: TStringField;
    Fili_C33_2: TStringField;
    Fili_C33_3: TStringField;
    Fili_C33_4: TStringField;
    Fili_C33_5: TStringField;
    Fili_C33_6: TStringField;
    Fili_C33_7: TStringField;
    Fili_C33_8: TStringField;
    Fili_C33_9: TStringField;
    Fili_C33_10: TSmallintField;
    Fili_C33_11: TStringField;
    Fili_C33_12: TStringField;
    Fili_C33_13: TStringField;
    Fili_C33_14: TStringField;
    Fili_C33_15: TStringField;
    Fili_C33_16: TStringField;
    Fili_C33_17: TIntegerField;
    Fili_C34_0: TSmallintField;
    Fili_C34_1: TStringField;
    Fili_C34_2: TSmallintField;
    Fili_C34_3: TStringField;
    Fili_C34_4: TStringField;
    Fili_C34_5: TStringField;
    Fili_C35_0: TStringField;
    Fili_C35_1: TStringField;
    Fili_C35_2: TStringField;
    Fili_C36_0: TStringField;
    Fili_C36_1: TStringField;
    Fili_C36_2: TStringField;
    Fili_C36_3: TStringField;
    Fili_C37_0: TStringField;
    Fili_C37_1: TStringField;
    Fili_C37_2: TStringField;
    Fili_C37_3: TStringField;
    Fili_C37_4: TStringField;
    Fili_C37_5: TStringField;
    Fili_C37_6: TStringField;
    Fili_C37_7: TStringField;
    Fili_C37_8: TStringField;
    Fili_C37_9: TStringField;
    Fili_C37_10: TSmallintField;
    Fili_C37_11: TStringField;
    Fili_C37_12: TStringField;
    Fili_C37_13: TStringField;
    Fili_C37_14: TStringField;
    Fili_C37_15: TStringField;
    Fili_C37_16: TStringField;
    Fili_C37_17: TIntegerField;
    Fili_C38_0: TSmallintField;
    Fili_C38_1: TStringField;
    Fili_C38_2: TStringField;
    Fili_C38_3: TStringField;
    Fili_C38_4: TStringField;
    Fili_C38_5: TStringField;
    Fili_C38_6: TStringField;
    Fili_C38_7: TStringField;
    Fili_C39_0: TStringField;
    Fili_C39_1: TStringField;
    Fili_C39_2: TStringField;
    Fili_C39_3: TStringField;
    Fili_C39_4: TStringField;
    Fili_C39_5: TStringField;
    Fili_C39_6: TStringField;
    Fili_C39_7: TStringField;
    Fili_C39_8: TStringField;
    Fili_C39_9: TStringField;
    Fili_C39_10: TSmallintField;
    Fili_C39_11: TStringField;
    Fili_C39_12: TStringField;
    Fili_C39_13: TStringField;
    Fili_C39_14: TStringField;
    Fili_C39_15: TStringField;
    Fili_C39_16: TStringField;
    Fili_C39_17: TIntegerField;
    Fili_C40_0: TStringField;
    Fili_C40_1: TStringField;
    Fili_C40_2: TStringField;
    Fili_C40_3: TStringField;
    Fili_C40_4: TStringField;
    Fili_C40_5: TStringField;
    Fili_C40_6: TStringField;
    Fili_C40_7: TStringField;
    Fili_C40_8: TStringField;
    Fili_C40_9: TStringField;
    Fili_C40_10: TSmallintField;
    Fili_C40_11: TStringField;
    Fili_C40_12: TStringField;
    Fili_C40_13: TStringField;
    Fili_C40_14: TStringField;
    Fili_C40_15: TStringField;
    Fili_C40_16: TStringField;
    Fili_C40_17: TIntegerField;
    Fili_C41_0: TStringField;
    Fili_C41_1: TStringField;
    Fili_C41_2: TStringField;
    Fili_C41_3: TStringField;
    Fili_C41_4: TStringField;
    Fili_C41_5: TStringField;
    Fili_C41_6: TStringField;
    Fili_C41_7: TStringField;
    Fili_C41_8: TStringField;
    Fili_C41_9: TStringField;
    Fili_C41_10: TSmallintField;
    Fili_C41_11: TStringField;
    Fili_C41_12: TStringField;
    Fili_C41_13: TStringField;
    Fili_C41_14: TStringField;
    Fili_C41_15: TStringField;
    Fili_C41_16: TStringField;
    Fili_C41_17: TIntegerField;
    Fili_C42_0: TStringField;
    Fili_C42_1: TStringField;
    Fili_C43_0: TSmallintField;
    Fili_C43_1: TSmallintField;
    Fili_C43_2: TStringField;
    Fili_C44_0: TStringField;
    Fili_C44_1: TStringField;
    Fili_C44_2: TStringField;
    Fili_C45_0: TStringField;
    Fili_C45_1: TStringField;
    Fili_C45_2: TStringField;
    Fili_C45_3: TStringField;
    Fili_C46_0: TStringField;
    Fili_C46_1: TStringField;
    Fili_C46_2: TStringField;
    Fili_C47_0: TSmallintField;
    Fili_C47_1: TStringField;
    Fili_C47_2: TSmallintField;
    Fili_C47_3: TStringField;
    Fili_C47_4: TStringField;
    Fili_C47_5: TStringField;
    HYEdit9: THYEdit;
    bProces_C_Motiu: TIntegerField;
    bProces_C0_0: TIntegerField;
    bProces_C0_1: TStringField;
    bProces_C0_2: TStringField;
    bProces_C0_3: TIntegerField;
    bProces_C0_4: TStringField;
    bProces_C0_5: TStringField;
    bProces_C0_6: TStringField;
    bProces_C0_7: TStringField;
    bProces_C0_8: TSmallintField;
    bProces_C0_9: TSmallintField;
    bProces_C0_10: TStringField;
    bProces_C0_11: TStringField;
    bProces_C0_12: TDateTimeField;
    bProces_C0_13: TStringField;
    bProces_C0_14: TStringField;
    bProces_C0_15: TStringField;
    bProces_C0_16: TStringField;
    bProces_C0_17: TSmallintField;
    bProces_C0_18: TSmallintField;
    bProces_C0_19: TStringField;
    bProces_C0_20: TStringField;
    bProces_C0_21: TStringField;
    bProces_C0_22: TStringField;
    bProces_C0_23: TStringField;
    bProces_C0_24: TSmallintField;
    bProces_C0_25: TStringField;
    bProces_C0_26: TSmallintField;
    bProces_C0_27: TStringField;
    bProces_C0_28: TStringField;
    bProces_C0_29: TStringField;
    bProces_C0_30: TIntegerField;
    bProces_C1_0: TSmallintField;
    bProces_C1_1: TStringField;
    bProces_C1_2: TSmallintField;
    bProces_C1_3: TStringField;
    bProces_C1_4: TStringField;
    bProces_C1_5: TStringField;
    DBText1: TDBText;
    bPautes_SegueixProtocolDurada: TStringField;
    bPautes_SegueixProtocolFreq: TStringField;
    bPautes_C0_0: TIntegerField;
    bPautes_C0_1: TIntegerField;
    bPautes_C0_2: TDateTimeField;
    bPautes_C1_0: TIntegerField;
    bPautes_C1_1: TIntegerField;
    bPautes_C1_2: TStringField;
    bPautes_C1_3: TDateTimeField;
    bPautes_C1_4: TDateTimeField;
    bPautes_C1_5: TDateTimeField;
    bPautes_C1_6: TStringField;
    bPautes_C1_7: TStringField;
    bPautes_C1_8: TStringField;
    bPautes_C1_9: TFloatField;
    bPautes_C1_10: TStringField;
    bPautes_C1_11: TStringField;
    bPautes_C1_12: TStringField;
    bPautes_C1_13: TStringField;
    bPautes_C1_14: TSmallintField;
    bPautes_C1_15: TSmallintField;
    bPautes_C1_16: TSmallintField;
    bPautes_C1_17: TStringField;
    bPautes_C1_18: TStringField;
    bPautes_C1_19: TStringField;
    bPautes_C1_20: TIntegerField;
    bPautes_C1_21: TStringField;
    bPautes_C1_22: TStringField;
    bPautes_C1_23: TStringField;
    bPautes_C1_24: TStringField;
    bPautes_C1_25: TStringField;
    bPautes_C1_26: TStringField;
    bPautes_C1_27: TStringField;
    bPautes_C1_28: TDateTimeField;
    bPautes_C1_29: TIntegerField;
    bPautes_C2_0: TStringField;
    bPautes_C2_1: TStringField;
    bPautes_C2_2: TStringField;
    bPautes_C2_3: TStringField;
    bPautes_C2_4: TStringField;
    bPautes_C2_5: TStringField;
    bPautes_C2_6: TStringField;
    bPautes_C2_7: TIntegerField;
    bPautes_C2_8: TStringField;
    bPautes_C2_9: TStringField;
    bPautes_C2_10: TSmallintField;
    bPautes_C2_11: TStringField;
    bPautes_C2_12: TStringField;
    bPautes_C2_13: TStringField;
    bPautes_C2_14: TStringField;
    bPautes_C2_15: TStringField;
    bPautes_C2_16: TIntegerField;
    bPautes_C2_17: TDateTimeField;
    bPautes_C3_0: TStringField;
    bPautes_C3_1: TStringField;
    bPautes_C3_2: TStringField;
    bPautes_C3_3: TStringField;
    bPautes_C3_4: TStringField;
    bPautes_C3_5: TStringField;
    bPautes_C3_6: TStringField;
    bPautes_C3_7: TIntegerField;
    bPautes_C3_8: TStringField;
    bPautes_C3_9: TStringField;
    bPautes_C3_10: TSmallintField;
    bPautes_C3_11: TStringField;
    bPautes_C3_12: TStringField;
    bPautes_C3_13: TStringField;
    bPautes_C3_14: TStringField;
    bPautes_C3_15: TStringField;
    bPautes_C3_16: TIntegerField;
    bPautes_C3_17: TDateTimeField;
    bPautes_C4_0: TSmallintField;
    bPautes_C4_1: TStringField;
    bPautes_C4_2: TSmallintField;
    bPautes_C4_3: TStringField;
    bPautes_C4_4: TStringField;
    bPautes_C4_5: TStringField;
    bTorns_ID: TIntegerField;
    bTorns_C0_0: TIntegerField;
    bTorns_C0_1: TIntegerField;
    bTorns_C0_2: TDateTimeField;
    bTorns_C1_0: TStringField;
    bTorns_C1_1: TStringField;
    bTorns_C1_2: TStringField;
    bTorns_C1_3: TStringField;
    bTorns_C1_4: TSmallintField;
    bTorns_C2_0: TStringField;
    bTorns_C2_1: TStringField;
    bTorns_C2_2: TStringField;
    bTorns_C2_3: TStringField;
    bTorns_C2_4: TStringField;
    bTorns_C2_5: TStringField;
    bTorns_C2_6: TStringField;
    bTorns_C2_7: TIntegerField;
    bTorns_C2_8: TStringField;
    bTorns_C2_9: TStringField;
    bTorns_C2_10: TSmallintField;
    bTorns_C2_11: TStringField;
    bTorns_C2_12: TStringField;
    bTorns_C2_13: TStringField;
    bTorns_C2_14: TStringField;
    bTorns_C2_15: TStringField;
    bTorns_C2_16: TIntegerField;
    bTorns_C2_17: TDateTimeField;
    bTorns_C3_0: TSmallintField;
    bTorns_C3_1: TStringField;
    bTorns_C3_2: TSmallintField;
    bTorns_C3_3: TStringField;
    bTorns_C3_4: TStringField;
    bTorns_C3_5: TStringField;
    Tract_C_Prescriptor: TStringField;
    Tract_C_MEF: TStringField;
    Tract_C_TRANSPORT_SANITARI: TSmallintField;
    Tract_C_Modalitat: TSmallintField;
    Tract_C0_0: TIntegerField;
    Tract_C0_1: TStringField;
    Tract_C0_2: TStringField;
    Tract_C0_3: TIntegerField;
    Tract_C0_4: TStringField;
    Tract_C0_5: TStringField;
    Tract_C0_6: TStringField;
    Tract_C0_7: TStringField;
    Tract_C0_8: TSmallintField;
    Tract_C0_9: TSmallintField;
    Tract_C0_10: TStringField;
    Tract_C0_11: TStringField;
    Tract_C0_12: TDateTimeField;
    Tract_C0_13: TStringField;
    Tract_C0_14: TStringField;
    Tract_C0_15: TStringField;
    Tract_C0_16: TStringField;
    Tract_C0_17: TSmallintField;
    Tract_C0_18: TSmallintField;
    Tract_C0_19: TStringField;
    Tract_C0_20: TStringField;
    Tract_C0_21: TStringField;
    Tract_C0_22: TStringField;
    Tract_C0_23: TStringField;
    Tract_C0_24: TSmallintField;
    Tract_C0_25: TStringField;
    Tract_C0_26: TSmallintField;
    Tract_C0_27: TStringField;
    Tract_C0_28: TStringField;
    Tract_C0_29: TStringField;
    Tract_C0_30: TIntegerField;
    Tract_C1_0: TStringField;
    Tract_C1_1: TStringField;
    Tract_C1_2: TStringField;
    Tract_C1_3: TStringField;
    Tract_C1_4: TSmallintField;
    Tract_C1_5: TStringField;
    Tract_C1_6: TStringField;
    Tract_C1_7: TSmallintField;
    Tract_C1_8: TStringField;
    Tract_C2_0: TStringField;
    Tract_C2_1: TStringField;
    Tract_C2_2: TStringField;
    Tract_C2_3: TStringField;
    Tract_C2_4: TStringField;
    Tract_C2_5: TStringField;
    Tract_C2_6: TStringField;
    Tract_C2_7: TIntegerField;
    Tract_C2_8: TStringField;
    Tract_C2_9: TStringField;
    Tract_C2_10: TSmallintField;
    Tract_C2_11: TStringField;
    Tract_C2_12: TStringField;
    Tract_C2_13: TStringField;
    Tract_C2_14: TStringField;
    Tract_C2_15: TStringField;
    Tract_C2_16: TIntegerField;
    Tract_C2_17: TDateTimeField;
    Tract_C3_0: TStringField;
    Tract_C3_1: TStringField;
    Tract_C3_2: TStringField;
    Tract_C3_3: TStringField;
    Tract_C3_4: TStringField;
    Tract_C3_5: TStringField;
    Tract_C3_6: TStringField;
    Tract_C3_7: TIntegerField;
    Tract_C3_8: TStringField;
    Tract_C3_9: TStringField;
    Tract_C3_10: TSmallintField;
    Tract_C3_11: TStringField;
    Tract_C3_12: TStringField;
    Tract_C3_13: TStringField;
    Tract_C3_14: TStringField;
    Tract_C3_15: TStringField;
    Tract_C3_16: TIntegerField;
    Tract_C3_17: TDateTimeField;
    Tract_C4_0: TStringField;
    Tract_C4_1: TStringField;
    Tract_C4_2: TStringField;
    Tract_C4_3: TStringField;
    Tract_C4_4: TStringField;
    Tract_C4_5: TStringField;
    Tract_C4_6: TStringField;
    Tract_C4_7: TIntegerField;
    Tract_C4_8: TStringField;
    Tract_C4_9: TStringField;
    Tract_C4_10: TSmallintField;
    Tract_C4_11: TStringField;
    Tract_C4_12: TStringField;
    Tract_C4_13: TStringField;
    Tract_C4_14: TStringField;
    Tract_C4_15: TStringField;
    Tract_C4_16: TIntegerField;
    Tract_C4_17: TDateTimeField;
    Tract_C5_0: TSmallintField;
    Tract_C5_1: TStringField;
    Tract_C6_0: TSmallintField;
    Tract_C6_1: TStringField;
    Tract_C7_0: TSmallintField;
    Tract_C7_1: TStringField;
    Tract_C7_2: TStringField;
    Tract_C7_3: TStringField;
    Tract_C7_4: TStringField;
    Tract_C7_5: TStringField;
    Tract_C7_6: TStringField;
    Tract_C7_7: TStringField;
    Tract_C8_0: TSmallintField;
    Tract_C8_1: TStringField;
    Tract_C9_0: TSmallintField;
    Tract_C9_1: TStringField;
    Tract_C10_0: TSmallintField;
    Tract_C10_1: TStringField;
    Tract_C10_2: TSmallintField;
    Tract_C10_3: TStringField;
    Tract_C10_4: TStringField;
    Tract_C10_5: TStringField;
    Tract_C11_0: TSmallintField;
    Tract_C11_1: TStringField;
    Tract_C11_2: TStringField;
    Tract_C11_3: TStringField;
    Tract_C11_4: TStringField;
    Tract_C11_5: TStringField;
    Tract_C11_6: TStringField;
    Tract_C11_7: TStringField;
    Tract_C12_0: TStringField;
    Tract_C12_1: TStringField;
    Tract_C12_2: TStringField;
    Tract_C12_3: TStringField;
    Tract_C12_4: TSmallintField;
    Tract_C13_0: TStringField;
    Tract_C13_1: TStringField;
    Tract_C13_2: TStringField;
    Tract_C13_3: TStringField;
    Tract_C13_4: TStringField;
    Tract_C13_5: TStringField;
    Tract_C13_6: TStringField;
    Tract_C13_7: TIntegerField;
    Tract_C13_8: TStringField;
    Tract_C13_9: TStringField;
    Tract_C13_10: TSmallintField;
    Tract_C13_11: TStringField;
    Tract_C13_12: TStringField;
    Tract_C13_13: TStringField;
    Tract_C13_14: TStringField;
    Tract_C13_15: TStringField;
    Tract_C13_16: TIntegerField;
    Tract_C13_17: TDateTimeField;
    Tract_C14_0: TStringField;
    Tract_C14_1: TStringField;
    Tract_C14_2: TStringField;
    Tract_C14_3: TStringField;
    Tract_C14_4: TStringField;
    Tract_C14_5: TStringField;
    Tract_C14_6: TStringField;
    Tract_C14_7: TIntegerField;
    Tract_C14_8: TStringField;
    Tract_C14_9: TStringField;
    Tract_C14_10: TSmallintField;
    Tract_C14_11: TStringField;
    Tract_C14_12: TStringField;
    Tract_C14_13: TStringField;
    Tract_C14_14: TStringField;
    Tract_C14_15: TStringField;
    Tract_C14_16: TIntegerField;
    Tract_C14_17: TDateTimeField;
    Tract_C15_0: TSmallintField;
    Tract_C15_1: TStringField;
    Tract_C15_2: TSmallintField;
    Tract_C15_3: TStringField;
    Tract_C15_4: TStringField;
    Tract_C15_5: TStringField;
    Tract_C16_0: TSmallintField;
    Tract_C16_1: TStringField;
    Tract_C16_2: TSmallintField;
    Tract_C16_3: TStringField;
    Tract_C16_4: TStringField;
    Tract_C16_5: TStringField;
    Tract_C17_0: TStringField;
    Tract_C17_1: TStringField;
    Tract_C17_2: TStringField;
    Tract_C17_3: TStringField;
    Tract_C17_4: TStringField;
    Tract_C17_5: TStringField;
    Tract_C17_6: TStringField;
    Tract_C17_7: TStringField;
    Tract_C17_8: TStringField;
    Tract_C17_9: TStringField;
    Tract_C17_10: TSmallintField;
    Tract_C17_11: TStringField;
    Tract_C17_12: TStringField;
    Tract_C17_13: TStringField;
    Tract_C17_14: TStringField;
    Tract_C17_15: TStringField;
    Tract_C17_16: TStringField;
    Tract_C17_17: TIntegerField;
    Tract_C18_0: TStringField;
    Tract_C18_1: TStringField;
    Tract_C18_2: TStringField;
    Tract_C19_0: TStringField;
    Tract_C19_1: TStringField;
    Tract_C19_2: TStringField;
    Tract_C19_3: TStringField;
    Tract_C19_4: TStringField;
    Tract_C19_5: TStringField;
    Tract_C20_0: TStringField;
    Tract_C20_1: TStringField;
    Tract_C20_2: TStringField;
    Tract_C20_3: TStringField;
    Tract_C20_4: TStringField;
    Tract_C20_5: TStringField;
    Tract_C20_6: TStringField;
    Tract_C20_7: TStringField;
    Tract_C20_8: TStringField;
    Tract_C20_9: TStringField;
    Tract_C20_10: TStringField;
    Tract_C20_11: TStringField;
    Tract_C20_12: TStringField;
    Tract_C20_13: TFloatField;
    Tract_C20_14: TIntegerField;
    Tract_C20_15: TStringField;
    Tract_C20_16: TIntegerField;
    Tract_C20_17: TStringField;
    Tract_C21_0: TStringField;
    Tract_C21_1: TStringField;
    Tract_C21_2: TStringField;
    Tract_C21_3: TStringField;
    Tract_C21_4: TStringField;
    Tract_C21_5: TStringField;
    Tract_C21_6: TStringField;
    Tract_C21_7: TStringField;
    Tract_C21_8: TStringField;
    Tract_C21_9: TStringField;
    Tract_C21_10: TSmallintField;
    Tract_C21_11: TStringField;
    Tract_C21_12: TStringField;
    Tract_C21_13: TStringField;
    Tract_C21_14: TStringField;
    Tract_C21_15: TStringField;
    Tract_C21_16: TStringField;
    Tract_C21_17: TIntegerField;
    Tract_C22_0: TStringField;
    Tract_C22_1: TStringField;
    Tract_C22_2: TSmallintField;
    Tract_C23_0: TStringField;
    Tract_C23_1: TStringField;
    Tract_C23_2: TSmallintField;
    Tract_C23_3: TSmallintField;
    Tract_C24_0: TSmallintField;
    Tract_C24_1: TStringField;
    Tract_C24_2: TSmallintField;
    Tract_C24_3: TStringField;
    Tract_C24_4: TStringField;
    Tract_C24_5: TStringField;
    Tract_C25_0: TSmallintField;
    Tract_C25_1: TStringField;
    Tract_C25_2: TSmallintField;
    Tract_C25_3: TStringField;
    Tract_C25_4: TStringField;
    Tract_C25_5: TStringField;
    Tract_C26_0: TSmallintField;
    Tract_C26_1: TStringField;
    Tract_C26_2: TSmallintField;
    Tract_C26_3: TStringField;
    Tract_C26_4: TStringField;
    Tract_C26_5: TStringField;
    Tract_C27_0: TSmallintField;
    Tract_C27_1: TStringField;
    Tract_C27_2: TSmallintField;
    Tract_C27_3: TStringField;
    Tract_C27_4: TStringField;
    Tract_C27_5: TStringField;
    Tract_C28_0: TIntegerField;
    Tract_C28_1: TStringField;
    Tract_C28_2: TStringField;
    Tract_C28_3: TSmallintField;
    Tract_C28_4: TStringField;
    Tract_C29_0: TSmallintField;
    Tract_C29_1: TStringField;
    Tract_C29_2: TSmallintField;
    Tract_C29_3: TStringField;
    Tract_C29_4: TStringField;
    Tract_C29_5: TStringField;
    Tract_C30_0: TSmallintField;
    Tract_C30_1: TStringField;
    Tract_C30_2: TSmallintField;
    Tract_C30_3: TStringField;
    Tract_C30_4: TStringField;
    Tract_C30_5: TStringField;
    Tract_C31_0: TSmallintField;
    Tract_C31_1: TStringField;
    Tract_C31_2: TSmallintField;
    Tract_C31_3: TStringField;
    Tract_C31_4: TStringField;
    Tract_C31_5: TStringField;
    Tract_C32_0: TIntegerField;
    Tract_C32_1: TStringField;
    Tract_C32_2: TStringField;
    Tract_C32_3: TStringField;
    Tract_C32_4: TStringField;
    Tract_C32_5: TStringField;
    Tract_C32_6: TStringField;
    Tract_C32_7: TStringField;
    Tract_C32_8: TStringField;
    Tract_C32_9: TStringField;
    Tract_C32_10: TStringField;
    Tract_C32_11: TStringField;
    Tract_C32_12: TStringField;
    Tract_C32_13: TStringField;
    Tract_C33_0: TSmallintField;
    Tract_C33_1: TStringField;
    Tract_C33_2: TSmallintField;
    Tract_C33_3: TStringField;
    Tract_C33_4: TStringField;
    Tract_C33_5: TStringField;
    Tract_C34_0: TIntegerField;
    Tract_C34_1: TStringField;
    Tract_C34_2: TStringField;
    Tract_C34_3: TStringField;
    Tract_C34_4: TStringField;
    Tract_C35_0: TStringField;
    Tract_C35_1: TStringField;
    Tract_C35_2: TStringField;
    Tract_C35_3: TStringField;
    Tract_C35_4: TStringField;
    Tract_C35_5: TStringField;
    Tract_C35_6: TStringField;
    Tract_C35_7: TStringField;
    Tract_C35_8: TStringField;
    Tract_C35_9: TStringField;
    Tract_C35_10: TSmallintField;
    Tract_C35_11: TStringField;
    Tract_C35_12: TStringField;
    Tract_C35_13: TStringField;
    Tract_C35_14: TStringField;
    Tract_C35_15: TStringField;
    Tract_C35_16: TStringField;
    Tract_C35_17: TIntegerField;
    Tract_C36_0: TStringField;
    Tract_C36_1: TStringField;
    Tract_C36_2: TStringField;
    Tract_C36_3: TStringField;
    Tract_C36_4: TStringField;
    Tract_C36_5: TStringField;
    Tract_C36_6: TStringField;
    Tract_C36_7: TStringField;
    Tract_C36_8: TStringField;
    Tract_C36_9: TStringField;
    Tract_C36_10: TSmallintField;
    Tract_C36_11: TStringField;
    Tract_C36_12: TStringField;
    Tract_C36_13: TStringField;
    Tract_C36_14: TStringField;
    Tract_C36_15: TStringField;
    Tract_C36_16: TStringField;
    Tract_C36_17: TIntegerField;
    Tract_C37_0: TStringField;
    Tract_C37_1: TStringField;
    Tract_C38_0: TSmallintField;
    Tract_C38_1: TStringField;
    Tract_C38_2: TSmallintField;
    Tract_C38_3: TStringField;
    Tract_C38_4: TStringField;
    Tract_C38_5: TStringField;
    Tract_C39_0: TStringField;
    Tract_C39_1: TStringField;
    Tract_C39_2: TStringField;
    Tract_C39_3: TStringField;
    Tract_C39_4: TStringField;
    Tract_C39_5: TStringField;
    Tract_C39_6: TStringField;
    Tract_C39_7: TIntegerField;
    Tract_C39_8: TStringField;
    Tract_C39_9: TStringField;
    Tract_C39_10: TSmallintField;
    Tract_C39_11: TStringField;
    Tract_C39_12: TStringField;
    Tract_C39_13: TStringField;
    Tract_C39_14: TStringField;
    Tract_C39_15: TStringField;
    Tract_C39_16: TIntegerField;
    Tract_C39_17: TDateTimeField;
    Tract_C40_0: TStringField;
    Tract_C40_1: TStringField;
    Tract_C40_2: TStringField;
    Tract_C40_3: TStringField;
    Tract_C40_4: TStringField;
    Tract_C40_5: TStringField;
    Tract_C40_6: TStringField;
    Tract_C40_7: TIntegerField;
    Tract_C40_8: TStringField;
    Tract_C40_9: TStringField;
    Tract_C40_10: TSmallintField;
    Tract_C40_11: TStringField;
    Tract_C40_12: TStringField;
    Tract_C40_13: TStringField;
    Tract_C40_14: TStringField;
    Tract_C40_15: TStringField;
    Tract_C40_16: TIntegerField;
    Tract_C40_17: TDateTimeField;
    Tract_C41_0: TSmallintField;
    Tract_C41_1: TStringField;
    Tract_C41_2: TSmallintField;
    Tract_C41_3: TStringField;
    Tract_C41_4: TStringField;
    Tract_C41_5: TStringField;
    Tract_C42_0: TSmallintField;
    Tract_C42_1: TStringField;
    TractALTRESPROCEDIMENTS: TStringField;
    TractENQUESTA: TStringField;
    Ed_Tract_C_Modalitat: THYEdit;
    Eti_Tract_modalitat_N_Codi: THYLabel;
    procedure bAplicaFiltreClick(Sender: TObject);
    procedure FormCloseQuery(Sender: TObject; var CanClose: Boolean);
    procedure FormClose(Sender: TObject; var Action: TCloseAction);
    procedure bNetejaFiltreClick(Sender: TObject);
    procedure bAplicaSQLClick(Sender: TObject);
    procedure TractAfterScroll(DataSet: TDataSet);
    procedure bProcesAfterScroll(DataSet: TDataSet);
    procedure PageControl1Change(Sender: TObject);
  private
  public
     procedure Iniciar(Tractament: Integer = -1);
  end;

var
  wFichaTractaments: TwFichaTractaments;

implementation

uses DataBasics, Data, DataCurs, DataAdmisio, DataPerfilsNR;

{$R *.DFM}


Procedure TwFichaTractaments.Iniciar(Tractament: Integer = -1);
begin
    if (Tractament <> -1) then
    begin
        fTractament.Valor1 := IntToStr(Tractament);
        fTractament.Condicion := tiIgual;
        bAplicaFiltreClick(bAplicaFiltre);
    end;
end;


procedure TwFichaTractaments.bAplicaFiltreClick(Sender: TObject);
var
  cond: String;
begin
    TractCodificacio.Close;
    DiagI.Close;
    DiagP.Close;
    DiagA.Close;
    Procediments.Close;
    DeficitsI.Close;
    DeficitsP.Close;
    DeficitsA.Close;
    tPermisos.Close;
    tPermisosLog.Close;
    Fili.Close;
    Tract.Close;

    with Busca do
    begin
        Close;
        SQL.Clear;

        SQL.Add('select T.C_TRACTAMENT, T.C_PROCES, T.C_HISTORIA, F.NOMCOMPLET, T.C_PRESTACIO, T.DATA_INGRES, T.C_COORDINADOR');
        SQL.Add('from TRACTAMENTS T');
        SQL.Add('join FILIACIO F on T.C_HISTORIA = F.NUM_HIST');

        cond := 'where ';
        if fTractament.HayFiltro  then begin SQL.Add(cond); SQL.Add(fTractament.Filtro);  cond := 'and '; end;
        if fProces.HayFiltro      then begin SQL.Add(cond); SQL.Add(fProces.Filtro);      cond := 'and '; end;
        if fHistoria.HayFiltro    then begin SQL.Add(cond); SQL.Add(fHistoria.Filtro);    cond := 'and '; end;
        if fNom.HayFiltro         then begin SQL.Add(cond); SQL.Add(fNom.Filtro);         cond := 'and '; end;
        if fPrestacio.HayFiltro   then begin SQL.Add(cond); SQL.Add(fPrestacio.Filtro);   cond := 'and '; end;
        if fDataIngres.HayFiltro  then begin SQL.Add(cond); SQL.Add(fDataIngres.Filtro);  cond := 'and '; end;
        if fDataAlta.HayFiltro    then begin SQL.Add(cond); SQL.Add(fDataAlta.Filtro);    cond := 'and '; end;
        if fCoordinador.HayFiltro then begin SQL.Add(cond); SQL.Add(fCoordinador.Filtro); cond := 'and '; end;

        SQL.Add('order by T.C_HISTORIA, T.DATA_INGRES');

        Memo.Lines.Assign(SQL);
        Open;
    end;

    TractCodificacio.Open;
    DiagI.Open;
    DiagP.Open;
    DiagA.Open;
    Procediments.Open;
    DeficitsI.Open;
    DeficitsP.Open;
    DeficitsA.Open;
    Fili.Open;
    tPermisos.Open;
    tPermisosLog.Open;

    Tract.Open;          // si hi ha filtre del tractament 253406 (que té codis ICD 10 a diagnòstics) es penja.

    Busca.First;
end;


procedure TwFichaTractaments.FormCloseQuery(Sender: TObject; var CanClose: Boolean);
begin
    CanClose := Tract.PuedeCerrar and Fili.PuedeCerrar and
                bProces.PuedeCerrar and bPautes.PuedeCerrar and bTorns.PuedeCerrar and
                DiagI.PuedeCerrar and DiagP.PuedeCerrar and DiagA.PuedeCerrar and Procediments.PuedeCerrar and
                DeficitsI.PuedeCerrar and DeficitsP.PuedeCerrar and DeficitsA.PuedeCerrar and TractCodificacio.PuedeCerrar and
                tPermisos.PuedeCerrar and tPermisosLog.PuedeCerrar;
end;

procedure TwFichaTractaments.FormClose(Sender: TObject; var Action: TCloseAction);
begin
    Action := caFree;
end;


procedure TwFichaTractaments.bNetejaFiltreClick(Sender: TObject);
begin
    fTractament.Valor1  := '';  fTractament.Valor2  := '';
    fProces.Valor1      := '';  fProces.Valor2      := '';
    fHistoria.Valor1    := '';  fHistoria.Valor2    := '';
    fNom.Valor1         := '';  fNom.Valor2         := '';
    fPrestacio.Valor1   := '';  fPrestacio.Valor2   := '';
    fDataIngres.Valor1  := '';  fDataIngres.Valor2  := '';
    fDataAlta.Valor1    := '';  fDataAlta.Valor2    := '';
    fCoordinador.Valor1 := '';  fCoordinador.Valor2 := '';
end;

procedure TwFichaTractaments.bAplicaSQLClick(Sender: TObject);
begin
    TractCodificacio.Close;
    DiagI.Close;
    DiagP.Close;
    DiagA.Close;
    Procediments.Close;
    DeficitsI.Close;
    DeficitsP.Close;
    DeficitsA.Close;
    tPermisos.Close;
    tPermisosLog.Close;
    Fili.Close;
    Tract.Close;

    Busca.Close;
    Busca.SQL.Clear;
    Busca.SQL.Text := Memo.Text;
    Busca.Open;

    TractCodificacio.Open;
    DiagI.Open;
    DiagP.Open;
    DiagA.Open;
    Procediments.Open;
    DeficitsI.Open;
    DeficitsP.Open;
    DeficitsA.Open;
    tPermisos.open;
    tPermisosLog.Open;
    Fili.Open;
    Tract.Open;

    Busca.First;
end;



procedure TwFichaTractaments.TractAfterScroll(DataSet: TDataSet);
begin
    if (PageControl1.ActivePage = TabAmbulatori) then
    begin
        if not bProces.Active then
        begin
            bProces.Open;
            bPautes.Open;
            bTorns.Open;
        end;

        if Tract.FieldByName('C_Proces').IsNull then bProces.Last
                                                else bProces.Locate('C_PROCES', Tract.FieldByName('C_Proces').AsInteger, []);
    end
    else begin
        bProces.Close;
        bPautes.Close;
        bTorns.Close;
    end;
end;


procedure TwFichaTractaments.bProcesAfterScroll(DataSet: TDataSet);
begin
    if bPautes.Active and not bPautes.FieldByName('C_Proces').IsNull then bPautes.Last;
end;


procedure TwFichaTractaments.PageControl1Change(Sender: TObject);
begin
    if (PageControl1.ActivePage = TabAmbulatori) and Tract.Active then
    begin
        if not bProces.Active then
        begin
            bProces.Open;
            bPautes.Open;
            bTorns.Open;
        end;

        if Tract.FieldByName('C_Proces').IsNull then bProces.Last
                                                else bProces.Locate('C_PROCES', Tract.FieldByName('C_Proces').AsInteger, []);
    end
    else begin
        bProces.Close;
        bPautes.Close;
        bTorns.Close;
    end;
end;

end.
